s-fbo:  # name used for the dataset
  columns:  # Darwin Core fields to include and corresponding pandas dtypes
    institutionCode: str
    collectionCode: str
    catalogNumber: str
    occurrenceID: str  # required
    continent: str
    country: str
    countryCode: str
    locality: str
    stateProvince: str
    verbatimLocality: str
    higherGeography: str
    decimalLatitude: str  # required
    decimalLongitude: str  # required
    # geodeticDatum: str
    # coordinateUncertaintyInMeters: str
  distinctColumnSet:  # drop duplicate records for the subset of these columns
    - decimalLatitude
    - decimalLongitude
    - verbatimLocality
    - locality
  tokensExtraction:  # specifies location tokens extraction
    verbatimTokens:  # custom name to use for extracted tokens (must not be a Darwin Core field name)
        source: verbatimLocality  # Darwin Core source field for the tokens
        nerModelDir: 'models/ner-model'  # directory with a spaCy NER model
        longStrSep: ", "  # separator to use when concatenating all tokens in a string
        shortStrSep: ", " # separator to use when concatenating some of the tokens in a string
  peliasName: verbatimTokensStrLong  # Darwin Core field or concatenated tokens
  locationDisplayLabel: verbatimTokensStrShort # Darwin Core field or concatenated tokens

nhrs-nrm:
  columns:
    institutionCode: str
    collectionCode: str
    catalogNumber: str
    occurrenceID: str
    occurrenceRemarks: str
    continent: str
    country: str
    countryCode: str
    locality: str
    stateProvince: str
    higherGeography: str
    decimalLatitude: str
    decimalLongitude: str
    geodeticDatum: str
    coordinateUncertaintyInMeters: str
  distinctColumnSet:
    - decimalLatitude
    - decimalLongitude
    - locality
    - occurrenceRemarks
  tokensExtraction:
    verbatimTokens:
        source: occurrenceRemarks
        nerModelDir: 'models/ner-model'
        longStrSep: ", "
        shortStrSep: ", "
    interpretedTokens:
        source: locality
        nerModelDir: 'models/ner-model'
        longStrSep: ", "
        shortStrSep: ", "
  peliasName: locality
  locationDisplayLabel: interpretedTokensStrShort
